# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Un Ltd.
brief-intro: web log aggregations, brought to you by
blog-title: Web logs, ahoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ufo2mstar.github.io" # the base hostname & protocol for your site

permalink: post/:year/:month/:day/:title/

# other links
twitter_username: ufo2m
facebook_username: ufo2mstar
github_username: ufo2mstar
email: narensst@gmail.com
linkedIn_username: narenss
#dribbble_username:


description_footer: my other online exploits, if you are so inclined

# comments
# two ways to comment, only choose one, and use your own short name
# Two comments plugin, choose a just fine, use their own short_name
duoshuo_shortname: #hygblog
disqus_shortname: narenss

# statistic analysis
google_analytics_id: UA-26595428-2 # google analysis tracking id

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port: if you want something other than 4000 as a default
port: 80

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins:
  - jekyll-paginate
  - jekyll-feed
paginate: 6

#
#title: Your awesome title
#email: your-email@example.com
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
#
## Build settings
#markdown: kramdown
#theme: minima
#plugins:
#  - jekyll-feed
#
## Exclude from processing.
## The following items will not be processed, by default. Create a custom list
## to override the default setting.
## exclude:
##   - Gemfile
##   - Gemfile.lock
##   - node_modules
##   - vendor/bundle/
##   - vendor/cache/
##   - vendor/gems/
##   - vendor/ruby/