# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
source:      .
destination: ../_site

exclude:
 - Gemfile
 - Gemfile.lock

#$ jekyll build --config=_config.yml,_config_prod.yml
#
#Configuration file: _config.yml
#Configuration file: _config_prod.yml
#            Source: _source
#       Destination: _out
#      Generating...
#                    done.

# Site settings
title: Un Ltd.
brief-intro: web logs by
blog-title: Hello Fellow Earthling!

url: "https://ufo2mstar.github.io" # protocol and the base hostname for your site
baseurl: "" # the subpath of your site, e.g. /blog
#baseurl: "/blog" # the subpath of your site, e.g. /blog

permalink: blog/:year/:month/:day/:title/

share_facebook:
share_twitter:
share_reddit:

# other links
twitter_username: ufo2m
#facebook_username: ufo2mstar
github_username: ufo2mstar
email: narensst@gmail.com
linkedIn_username: narenss
aboutme_username: narenss
#dribbble_username:


description_footer: my other online exploits

# comments
# two ways to comment, only choose one, and use your own short name
# Two comments plugin, choose a just fine, use their own short_name
disqus_shortname: ufo2mstar-github-io

# statistic analysis
google_analytics_id: UA-26595428-2 # google analysis tracking id
#google_adsense_id: ca-pub-4526166921072328 # uncomment to advertise

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port: if you want something other than 4000 as a default
port: 80

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins:
  - jekyll-paginate
  - jemoji # for github flavored emojis :) :+1:
  - jekyll-relative-links # so that I dont have to do absolute pathing
  - jekyll-mermaid
  - jekyll-seo-tag
#  - jekyll-redirect-from # for vanity urls like domain/link, etc
#gems:
#  - jekyll-feed

relative_links:
  enabled:     true
  collections: false

mermaid:
#  src: 'js/mermaid.js'
  src: 'https://cdnjs.cloudflare.com/ajax/libs/mermaid/7.0.0/mermaid.min.js'

paginate: 10

# for dark theme
sass:
  style: compressed

repository: ufo2mstar/ufo2mstar.github.io
github: [metadata]
encoding: UTF-8
#kramdown:
#  input: GFM
#  hard_wrap: false

# TODO:
#https://medium.com/@allizadrozny/using-webpack-and-react-with-jekyll-cfe137f8a2cc
#https://blog.omc.io/elasticsearch-for-jekyll-part-1-ab456ac7c093
#Searchyll

